# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://demonkoo.github.io
date_format: "ordinal"
title: 码趣
subtitle: "不要怂，就是干"
description: "小古的代码笔记"
keywords: 码趣, Lilin Gu, demonkoo, 小古
favicon: /favicon.ico
timezone: Asia/HongKong
encoding: "utf-8"
source_code: https://github.com/demonkoo/demonkoo.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Koo
organization: ABC, Ltd
organization_url: http://www.abchina.com
location: Hong Kong, China
email: demonkoo1992@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: demonkoo

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# duoshuo_username: mazhuang
disqus_username: skyekoo
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-84502506-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Objective-C, C++, Swift]
skill_mobile_app_keywords: [iOS]
skill_windows_keywords: [Winform]
